// Shared Deci webview CSS. Theme variables only (light/dark/high-contrast
// safe); risk colours are the only semantic colours, always paired with a
// text label or icon. One accent (blue) for primary actions.
export const DECI_CSS = [
  "*{box-sizing:border-box}",
  "body{font-family:var(--vscode-font-family);font-size:var(--vscode-font-size);color:var(--vscode-foreground);background:var(--vscode-editor-background);margin:0;padding:0}",
  ".deci-wrap{max-width:1000px;margin:0 auto;padding:16px 24px 48px}",
  ".deci-full{margin:0;padding:0;height:100vh;display:flex;flex-direction:column}",
  "h1{font-size:20px;font-weight:600;margin:4px 0 12px}",
  ".deci-label{font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:var(--vscode-descriptionForeground);margin:0 0 4px}",
  ".stat-cards{display:flex;gap:12px;flex-wrap:wrap;margin:12px 0}",
  ".stat-card{border:1px solid var(--vscode-panel-border);border-radius:12px;padding:10px 16px;min-width:110px;background:var(--vscode-editorWidget-background)}",
  ".stat-card .v{font-size:20px;font-weight:600;font-family:var(--vscode-editor-font-family)}",
  ".stat-card .k{font-size:11px;color:var(--vscode-descriptionForeground)}",
  "table.deci-table{border-collapse:collapse;width:100%;font-size:12px;margin:8px 0}",
  "table.deci-table th,table.deci-table td{border:1px solid var(--vscode-panel-border);padding:6px 10px;text-align:left;vertical-align:top}",
  "table.deci-table th{background:var(--vscode-textCodeBlock-background);font-weight:600}",
  ".table-scroll{overflow:auto;border:1px solid var(--vscode-panel-border);border-radius:8px}",
  ".table-scroll table.deci-table{border:none;margin:0}",
  ".pill{display:inline-block;font-size:10px;font-weight:700;padding:1px 8px;border-radius:8px;white-space:nowrap}",
  ".pill-Critical{background:#ff6b6b44;color:var(--vscode-foreground)}",
  ".pill-High{background:#ffa24d44;color:var(--vscode-foreground)}",
  ".pill-Medium{background:#e8d44d33;color:var(--vscode-foreground)}",
  ".pill-Low{background:#5ec28f33;color:var(--vscode-foreground)}",
  ".dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px;vertical-align:baseline}",
  ".dot-Critical{background:#ff6b6b}.dot-High{background:#ffa24d}.dot-Medium{background:#e8d44d}.dot-Low{background:#5ec28f}",
  ".btn{font-size:12px;padding:5px 14px;border-radius:6px;border:1px solid var(--vscode-panel-border);background:var(--vscode-button-secondaryBackground);color:var(--vscode-button-secondaryForeground);cursor:pointer}",
  ".btn.primary{background:var(--vscode-button-background);color:var(--vscode-button-foreground);border-color:transparent}",
  ".btn:disabled{opacity:.5;cursor:not-allowed}",
  ".btn:focus-visible,a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,[tabindex]:focus-visible{outline:2px solid var(--vscode-focusBorder);outline-offset:1px}",
  ".row-btns{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}",
  ".chip{font-size:11px;padding:3px 10px;border-radius:12px;border:1px solid var(--vscode-panel-border);background:transparent;color:var(--vscode-foreground);cursor:pointer}",
  ".chip[aria-pressed=true]{background:var(--vscode-button-background);color:var(--vscode-button-foreground);border-color:transparent}",
  ".mono{font-family:var(--vscode-editor-font-family);font-size:12px}",
  ".muted{color:var(--vscode-descriptionForeground)}",
  ".card{border:1px solid var(--vscode-panel-border);border-radius:12px;padding:12px 16px;margin:12px 0;background:var(--vscode-editorWidget-background)}",
  ".empty{border:1px dashed var(--vscode-panel-border);border-radius:12px;padding:28px;text-align:center;color:var(--vscode-descriptionForeground)}",
  ".banner{border:1px solid var(--vscode-panel-border);border-left:4px solid var(--vscode-button-background);border-radius:8px;padding:8px 12px;margin:12px 0;font-size:12px}",
  ".banner.warn{border-left-color:#ffa24d}",
  ".seg{display:inline-flex;border:1px solid var(--vscode-panel-border);border-radius:8px;overflow:hidden}",
  ".seg button{border:none;background:transparent;color:var(--vscode-foreground);padding:5px 14px;font-size:12px;cursor:pointer}",
  ".seg button[aria-pressed=true]{background:var(--vscode-button-background);color:var(--vscode-button-foreground)}",
  "label.f{display:flex;flex-direction:column;gap:4px;font-size:12px;margin:8px 0}",
  "input[type=text],input[type=password],input[type=number],select,textarea{font-size:12px;padding:5px 8px;background:var(--vscode-input-background);color:var(--vscode-input-foreground);border:1px solid var(--vscode-input-border);border-radius:6px;font-family:inherit}",
  ".riskbar{display:flex;height:8px;border-radius:4px;overflow:hidden;margin:8px 0}",
  ".riskbar span{display:block;height:100%}",
  // diff review
  ".dr{display:flex;flex:1;min-height:0}",
  ".dr-left{width:260px;flex:none;border-right:1px solid var(--vscode-panel-border);overflow-y:auto;padding:8px}",
  ".dr-center{flex:1;min-width:0;overflow-y:auto;padding:8px 16px}",
  ".dr-right{width:320px;flex:none;border-left:1px solid var(--vscode-panel-border);overflow-y:auto;padding:8px}",
  ".file-row{padding:6px 8px;border-radius:8px;cursor:pointer;font-size:12px}",
  ".file-row:hover{background:var(--vscode-list-hoverBackground)}",
  ".file-row[aria-current=true]{background:var(--vscode-list-activeSelectionBackground)}",
  ".diff{font-family:var(--vscode-editor-font-family);font-size:12px;line-height:1.55;border:1px solid var(--vscode-panel-border);border-radius:8px;overflow:hidden;margin:8px 0}",
  ".dline{display:flex;white-space:pre-wrap;word-break:break-all}",
  ".dline .ln{flex:none;width:44px;text-align:right;padding:0 8px;color:var(--vscode-descriptionForeground);user-select:none}",
  ".dline .tx{flex:1;padding:0 8px;overflow-x:auto}",
  ".dline.add{background:var(--vscode-diffEditor-insertedTextBackground)}",
  ".dline.del{background:var(--vscode-diffEditor-removedTextBackground)}",
  ".dline.hunk{background:var(--vscode-textCodeBlock-background);color:var(--vscode-descriptionForeground)}",
  ".gutter{flex:none;width:22px;text-align:center;cursor:pointer;user-select:none}",
  ".gutter .mk{display:inline-block;width:14px;height:14px;line-height:14px;border-radius:50%;font-size:9px;font-weight:700}",
  ".mk-Critical{background:#ff6b6b;color:#000}.mk-High{background:#ffa24d;color:#000}.mk-Medium{background:#e8d44d;color:#000}.mk-Low{background:#5ec28f;color:#000}",
  ".finding{border:1px solid var(--vscode-panel-border);border-left:4px solid var(--vscode-panel-border);border-radius:8px;padding:8px 12px;margin:6px 0 6px 22px;font-size:12px;background:var(--vscode-editorWidget-background)}",
  ".finding.f-Critical{border-left-color:#ff6b6b}.finding.f-High{border-left-color:#ffa24d}.finding.f-Medium{border-left-color:#e8d44d}.finding.f-Low{border-left-color:#5ec28f}",
  ".note-thread{margin:6px 0 6px 22px;border:1px dashed var(--vscode-panel-border);border-radius:8px;padding:8px 12px;font-size:12px}",
  ".note{padding:6px 0;border-bottom:1px solid var(--vscode-panel-border)}",
  ".note:last-child{border-bottom:none}",
  ".note .who{font-size:11px;color:var(--vscode-descriptionForeground)}",
  ".note .txt{white-space:pre-wrap;margin:2px 0}",
  ".tabs{display:flex;gap:2px;border-bottom:1px solid var(--vscode-panel-border);margin-bottom:8px}",
  ".tabs button{border:none;background:transparent;color:var(--vscode-foreground);padding:6px 10px;font-size:12px;cursor:pointer;border-bottom:2px solid transparent}",
  ".tabs button[aria-selected=true]{border-bottom-color:var(--vscode-button-background);font-weight:600}",
  ".sec{border-bottom:1px solid var(--vscode-panel-border);padding:8px 4px}",
  ".sec-head{display:flex;align-items:center;width:100%;border:none;background:transparent;color:var(--vscode-foreground);font-size:12px;font-weight:600;padding:6px 4px;cursor:pointer}",
  ".tok-k{color:#c586c0}.tok-s{color:#ce9178}.tok-c{color:#6a9955}.tok-n{color:#b5cea8}",
  ".check{display:flex;gap:8px;align-items:flex-start;padding:6px 4px;border-bottom:1px solid var(--vscode-panel-border);font-size:12px}",
  ".logbox{font-family:var(--vscode-editor-font-family);font-size:11px;white-space:pre-wrap;background:var(--vscode-textCodeBlock-background);border-radius:6px;padding:8px;max-height:220px;overflow:auto;margin-top:6px}",
  ".opt-card{border:1px solid var(--vscode-panel-border);border-radius:12px;padding:12px;margin:8px 0}",
  ".opt-card.rec{border-color:var(--vscode-button-background)}",
  "@media (max-width:700px){.dr{flex-direction:column}.dr-left,.dr-right{width:100%;border:none;border-bottom:1px solid var(--vscode-panel-border);max-height:220px}.deci-wrap{padding:12px}}",
].join("\n");
