// AI operations: the real Deci features that consume providers.
// Each operation builds its own prompt from LOCAL analysis artifacts,
// routes to the configured provider/model for its operation kind, and
// returns the provider's words clearly labeled as AI-generated alongside
// the deterministic evidence they must not contradict.
//
// Boundary rules (enforced, not advised):
// - Only the explicit prompt text leaves the machine; the caller decides
//   what goes in (diff excerpts are capped).
// - Every result records handledBy (provider + model) for observability.
// - AI text is NEVER merged into deterministic findings; callers render it
//   in a separate, labeled section.

import {
  completeWithPolicy,
  resolveProvider,
  routeFor,
  routesFromEnv,
  type ChatMessage,
  type DeciOperation,
  type Policy,
  type PolicyIo,
  type ResolvedProvider,
} from "./providers.js";

export interface AiResult {
  /** Provider's words. Always labeled AI-generated by callers. */
  text: string;
  handledBy: { provider: string; model: string };
  operation: DeciOperation;
}

export interface AiContext {
  /** Resolved default provider (routing may override per operation). */
  defaultProvider: ResolvedProvider;
  /** Per-operation `provider[:model]` route overrides. */
  routes?: Partial<Record<DeciOperation, string>>;
  /** Retry/fallback policy. */
  policy?: Policy;
  io?: PolicyIo;
  env?: Record<string, string | undefined>;
}

function resolveForOp(ctx: AiContext, op: DeciOperation): ResolvedProvider {
  const routes = { ...routesFromEnv(ctx.env ?? {}), ...(ctx.routes ?? {}) };
  const { providerId, model } = routeFor(op, ctx.defaultProvider.spec.id, routes);
  if (providerId === ctx.defaultProvider.spec.id) {
    // Same provider: keep the default's endpoint/key, override model only.
    // A different provider NEVER inherits another provider's key/endpoint —
    // it resolves from its own configuration (env), or fails validation
    // loudly instead of sending credentials to the wrong place.
    return model ? { ...ctx.defaultProvider, model } : ctx.defaultProvider;
  }
  return resolveProvider({ provider: providerId, model: model ?? undefined }, ctx.env ?? {});
}

async function runOp(ctx: AiContext, op: DeciOperation, messages: ChatMessage[]): Promise<AiResult> {
  const provider = resolveForOp(ctx, op);
  const res = await completeWithPolicy({ messages }, provider, ctx.policy ?? {}, ctx.io ?? {});
  return { text: res.text, handledBy: res.handledBy, operation: op };
}

/** Short behavioral summary of a diff (capped excerpt — never the whole repo). */
export function explainChange(ctx: AiContext, args: { summary: string; files: string[]; diffExcerpt: string }): Promise<AiResult> {
  return runOp(ctx, "explain", [
    { role: "system", content: "You explain code changes concisely for reviewers. State only what the provided diff shows; mark anything uncertain as uncertain. No invented file names, symbols, or test results." },
    { role: "user", content: `Change summary: ${args.summary}\nFiles: ${args.files.slice(0, 20).join(", ")}\nDiff excerpt (may be truncated):\n${args.diffExcerpt.slice(0, 4000)}` },
  ]);
}

/** Second opinion on a test failure, grounded in the deterministic diagnosis. */
export function assistDiagnosis(ctx: AiContext, args: { testPath: string; summary: string; causes: string[]; logExcerpt: string }): Promise<AiResult> {
  return runOp(ctx, "diagnose", [
    { role: "system", content: "You help diagnose test failures. Reason only from the evidence given; separate confirmed causes from hypotheses; never invent stack frames, files, or fixes." },
    { role: "user", content: `Failing test: ${args.testPath}\nFailure: ${args.summary}\nDeterministic causes: ${args.causes.join(" | ")}\nLog excerpt:\n${args.logExcerpt.slice(0, 3000)}` },
  ]);
}

/** Render helper: AI section with provenance, kept apart from deterministic findings. */
export function renderAiMarkdown(result: AiResult, title: string): string {
  return [
    `## ${title} (AI-generated — ${result.handledBy.provider}:${result.handledBy.model})`,
    ``,
    result.text,
    ``,
    `_Generated by ${result.handledBy.provider} model ${result.handledBy.model} for operation \`${result.operation}\`. Verify against the evidence above; AI text never overrides deterministic findings._`,
    ``,
  ].join("\n");
}
